### ISSUE TITLE
dparse grammar must end in .g

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/dparser-R#2]
While trying to make the next issue I'm about to submit, I got an error:

[nmtran_grammar.txt](https://github.com/nlmixrdevelopment/dparser-R/files/4193321/nmtran_grammar.txt)

``` r
library(dparser)
grammar <- dparser::dparse("nmtran_grammar.txt")
#> C:/Users/BILLDE~1/AppData/Local/Temp/RtmpmarK4R/file289031cc373b.g:1: syntax error after 'nmtran_grammar'
#> Error in mkdparse(grammar, tmpf, grammar_ident = gram, ..., use_r_header = TRUE): Parser Fail: unable to parse grammar 'C:/Users/BILLDE~1/AppData/Local/Temp/RtmpmarK4R/file289031cc373b.g'
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
I just realized that the request here isn't clear.  Could the file extension requirement be relaxed to allow any extension and not just `.g`?

**Comment by mattfidler** [comment]
This should work.

**Comment by mattfidler** [comment]
This is fixed in the development version.
