### ISSUE TITLE
Help with Basic Grammar?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/dparser-R#3]
As suggested in the MikeKSmith/rspeaksnonmem#21, I'm trying to start on a NONMEM grammar.  But, I'm hitting a wall at a very simple level -- just trying to parse a number.  When I do the following (renaming the .txt file to .g as described in #2), I can't parse a simple number, and I don't see why there is an error.  I assume that I'm missing something basic, but I'd appreciate help:

Rename this file to end in .g: [nmtran_grammar.txt](https://github.com/nlmixrdevelopment/dparser-R/files/4193347/nmtran_grammar.txt)

This is on Windows, if that matters.

``` r
library(dparser)
grammar <- dparser::dparse("nmtran_grammar.g")
grammar(
  "123",
  fn=function(name, value, pos, depth){
    ## This prints the name, value, position and depth passed to the
    ##parsing function.
    cat(sprintf("name:%s;value:%s;pos:%s;depth:%s\n", name, value, pos,
                depth));
  }
)
#:1: syntax error after '3'
#Error in grammar("123", fn = function(name, value, pos, depth) { : 
#  syntax errors.
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
The most comprehensive grammar example I have is:

https://github.com/nlmixrdevelopment/RxODE/blob/master/inst/tran.g

**Comment by billdenney** [comment]
@mattfidler, I looked at tran.g as my example, but I'm still having issues.  Is there any way to get a more detailed error message than "syntax error" to help show where the underlying issue is originating?

**Comment by mattfidler** [comment]
Here is a working example based on `tran.g` parsing simple numbers

``` r
gram <- "// loop
everything : (statement)+ ;

statement
  : constant ;


// Lexer items //////////

// General

constant : decimalint | float1 | float2;

// Numbers
decimalintNo0: \"([1-9][0-9]*)\" $term -1;
decimalint: \"0|([1-9][0-9]*)\" $term -1;
string: \"\\\"([^\\\"\\\\]|\\\\[^])*\\\"\";
float1: \"([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\-\\+]?[0-9]+)?\" $term -2;
float2: \"[0-9]+[eE][\\-\\+]?[0-9]+\" $term -3;
identifier: \"[a-zA-Z_][a-zA-Z0-9_]*\" $term -4;
whitespace: ( \"[ \\t\\r\\n]+\" | singleLineComment )*;
singleLineComment: ';' \"[^\\n]*\";

"
writeLines(gram, "tmp.g")
grammar <- dparser::dparse("tmp.g")
unlink("tmp.g")

grammar(
  "123 1.2 1e-3",
  fn=function(name, value, pos, depth){
    ## This prints the name, value, position and depth passed to the
    ##parsing function.
    cat(sprintf("name:%s;value:%s;pos:%s;depth:%s\n", name, value, pos,
                depth));
  }
)
#> name:everything;value:123 1.2 1e-3;pos:-2;depth:0
#> name:everything__3;value:123 1.2 1e-3;pos:-2;depth:1
#> name:everything__2;value:123;pos:-2;depth:2
#> name:statement;value:123;pos:-2;depth:3
#> name:constant;value:123;pos:-2;depth:4
#> name:decimalint;value:123;pos:-2;depth:5
#> name:0|([1-9][0-9]*);value:123;pos:-1;depth:6
#> name:decimalint;value:123;pos:0;depth:5
#> name:constant;value:123;pos:0;depth:4
#> name:statement;value:123;pos:0;depth:3
#> name:everything__2;value:123;pos:0;depth:2
#> name:everything__3;value:123;pos:0;depth:1
#> name:everything__2;value:1.2;pos:-2;depth:2
#> name:statement;value:1.2;pos:-2;depth:3
#> name:constant;value:1.2;pos:-2;depth:4
#> name:float1;value:1.2;pos:-2;depth:5
#> name:([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\-\+]?[0-9]+)?;value:1.2;pos:-1;depth:6
#> name:float1;value:1.2;pos:0;depth:5
#> name:constant;value:1.2;pos:0;depth:4
#> name:statement;value:1.2;pos:0;depth:3
#> name:everything__2;value:1.2;pos:0;depth:2
#> name:everything__3;value:1.2;pos:1;depth:1
#> name:everything__2;value:1e-3;pos:-2;depth:2
#> name:statement;value:1e-3;pos:-2;depth:3
#> name:constant;value:1e-3;pos:-2;depth:4
#> name:float2;value:1e-3;pos:-2;depth:5
#> name:[0-9]+[eE][\-\+]?[0-9]+;value:1e-3;pos:-1;depth:6
#> name:float2;value:1e-3;pos:0;depth:5
#> name:constant;value:1e-3;pos:0;depth:4
#> name:statement;value:1e-3;pos:0;depth:3
#> name:everything__2;value:1e-3;pos:0;depth:2
#> name:everything__3;value:1e-3;pos:2;depth:1
#> name:everything;value:123 1.2 1e-3;pos:0;depth:0
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Unfortunately the default syntax error is not as nice as `gcc` or `clang`.  

Currently there is not a way in R to have a better error message, though it could be adapted by adding a custom C handler for errors.  This is what RxODE does

**Comment by billdenney** [comment]
Thanks for that example.

**Comment by mattfidler** [comment]
I have forgotten where the `nonmem` parser was posted, do you recall?

**Comment by billdenney** [comment]
https://github.com/EightPillars/nmtranprocessorcpp/tree/master/grammar

**Comment by mattfidler** [comment]
Hm. That isn't as similar as I thought it was;  According to John the grammars are similar;

It still may be faster to create a NONMEM parser from scratch rather than porting antlr to R (without the overhead of java)

There are other parsers in R, though but I think they all create a C source code and don't parse directly in R.

If you do create the parser, I can add the C components for the package so you don't have to have gcc on installed your system

**Comment by billdenney** [comment]
I saw the note that the ANTLR and dparser grammars are similar in the manual or FAQ, but it's not just a copy-paste operation.  I'm going to try the path of dparser without linking ANTLR to R.  (FYI, ANTLR can generate C++ code, so after the initial package creation, java isn't required to use the package.)

Assuming that I get that far, I'll definitely take you up on the help for the C needs of the package.

**Comment by mattfidler** [comment]
Great.  Good luck.

**Comment by billdenney** [comment]
I've solved my issue with a few more parentheses and building up slowly.

[nmtran_grammar.txt](https://github.com/nlmixrdevelopment/dparser-R/files/4194840/nmtran_grammar.txt)
