### ISSUE TITLE
Can I start the parser not at the top of the file?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/dparser-R#5]
The question may be:  What is the `start_state` argument for `dparse()`?

Specifically, I'd like to build the NONMEM grammar with testing for individual parts of the grammar.  For example, I'd like to be able to test the `$DATA` part of the parser when building it up as a package.  Is there a way that I can have the parser start by trying to parse `$DATA` instead of a whole control stream?

For example, if I have a parser rule named `section_data`, can I start the parser as though it were there and not at a top-level `control_stream` level?

**Comment by mattfidler** [comment]
No there isn't a way to specify where to start.  It parses from top to bottom. 

Still you can try to test the `$DATA` part of the parser by simply giving the parser various `$DATA` records.  The full parsing can eventually check for correct records and give an error if there is a mis-specified control control stream.

**Comment by billdenney** [comment]
OK, thanks for that confirmation.  I guessed that I couldn't.  I'll just make a minimal file with only the bare minimum information and only fill out the section that I'm trying to test.
