### ISSUE TITLE
How to interpret function arguments in grammar call?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/dparser-R#6]
Can you please help understand the arguments passed to 

I've written the simplest, nontrivial NONMEM parser that I can think of, and it appears to work on the example files (see below).  Now, I'm trying to interpret the 4 arguments to the grammar function (as described here: https://github.com/nlmixrdevelopment/dparser-R/blob/d5afaac15af41f7a7c3875bd86c94f2091998f15/man/dparse.Rd#L109-L114)

* `name` appears to be pretty straight-forward as the parser name or the lexer rule that is being matched.
* `value` also appears straight-forward as the value of all text matched.
* `pos` is difficult to interpret for me.  It appears to be negative when descending, -1 is when it has reached a leaf of the parse tree (I think it's referred to as a "terminal" in the dparser manual).  I don't understand how to interpret zero and positive values.
* `depth` appears to be the tree depth that has been parsed (how many steps from the first parser element at the top of the grammar file.

Can you help with interpretation of the `pos` and `depth` arguments?  (With an ask to perhaps document it in more detail in the help for `dparse()`?)

# Simplest grammar
```
control_stream :
        ( section section_content )+;

section : "$[A-Z]+";
section_content : "[^$]*";
```

**Comment by mattfidler** [comment]
An illustrated example helps me (and hopefully will help you) understand some of these pieces, but I have to expand your grammar to be a little more complex to illustrate what happens.

<details>

``` r
gram <- "// loop
control_stream :
        ( section section_content )+;

section: \"[$]\" \"[A-Z][A-Z][A-Z]\" \"[A-Z]*\";

section_content : \"[^$]*\";
"
writeLines(gram, "tmp.g")
grammar <- dparser::dparse("tmp.g")
unlink("tmp.g")

grammar(
  "$PROBLEM pro",
  fn=function(name, value, pos, depth){
    ## This prints the name, value, position and depth passed to the
    ##parsing function.
    cat(sprintf("name:%s;value:%s;pos:%s;depth:%s\n", name, value, pos,
                depth));
  }
)
#> name:control_stream;value:$PROBLEM pro;pos:-2;depth:0
#> name:control_stream__3;value:$PROBLEM pro;pos:-2;depth:1
#> name:control_stream__2;value:$PROBLEM pro;pos:-2;depth:2
#> name:section;value:$PROBLEM;pos:-2;depth:3
#> name:[$];value:$;pos:-1;depth:4
#> name:section;value:$;pos:0;depth:3
#> name:[A-Z][A-Z][A-Z];value:PRO;pos:-1;depth:4
#> name:section;value:PRO;pos:1;depth:3
#> name:[A-Z]*;value:BLEM;pos:-1;depth:4
#> name:section;value:BLEM;pos:2;depth:3
#> name:control_stream__2;value:$PROBLEM;pos:0;depth:2
#> name:section_content;value:pro;pos:-2;depth:3
#> name:[^$]*;value:pro;pos:-1;depth:4
#> name:section_content;value:pro;pos:0;depth:3
#> name:control_stream__2;value:pro;pos:1;depth:2
#> name:control_stream__3;value:$PROBLEM pro;pos:0;depth:1
#> name:control_stream;value:$PROBLEM pro;pos:0;depth:0
```

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>


* `name` is the rule being matched
* `value` is the value of the part being matched
* `pos` is the position in rule that the match is occurring.

Here I will focus on the `section: "[$]" "[A-Z][A-Z][A-Z]" "[A-Z]*";` expansion of your grammar

When `name` == `section`
`pos=0` when the match is `$`
`pos=1` when the match is `PRO`
`pos=2` when the match is `BLEM`

* `depth` is the tree depth.

**Comment by mattfidler** [comment]
I actually do not know what the negative `pos` values mean.

**Comment by billdenney** [comment]
OK, thanks for the quick response!
